apiVersion: v1
kind: Pod
metadata:
  name: config-map-pod
spec:
  containers:
    - name: config-map-pod
      image: busybox
      command: ['sh', '-c', 'printenv && sleep 3600' ]
      envFrom:
        - configMapRef:
            name: busybox-config-env
  restartPolicy: Never